### ISSUE TITLE
Run inference on SRD dataset

### ISSUE THREAD

**Issue by heorhiikalaichev** [tsingqguo/inpaint4shadow#3]
Hi!

I'm Thank you for your work!
Could you tell me how can I run inference using your model on the SRD dataset? It contains only images with shadow and without shadow. As I understand, your model requires `self.inpaint_model.process(images, masks, shadows)`.
Could you explain what are images, masks, and shadows in the case of the SRD dataset?

Thank you in advance.

**Comment by Li-Xiaoguang** [comment]
The images denote the shadow-free ground truth images (only used during the training), masks denote the binary shadow mask (which is detected by the existing method, because the SRD dataset does not provide the shadow mask), and shadows denote the shadow image. I hope the response is helpful!
