### ISSUE TITLE
how to calculate RMSE

### ISSUE THREAD

**Issue by zyt0929** [tsingqguo/inpaint4shadow#5]
I have looked at the method of calculating metrics psnr and ssim in your code. It seems that your method of calculating metrics is slightly different from the methods in other papers. I would like to know how your RMSE is calculated. Can you also include the RMSE calculation method in Evaluation. py

**Comment by Li-Xiaoguang** [comment]
Following the previous works, the final RMSE results reported in the paper are calculated by the [matlab script](https://drive.google.com/file/d/1SAMqLy3dSONPgeC5ZQskPoeq60FEx9Vk/view)

We use the following methods to calculate  PSNR and SSIM:
from skimage.metrics import peak_signal_noise_ratio as compare_psnr
from skimage.metrics import structural_similarity as compare_ssim
